name: Build iOS App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kabiroberai/theos-docker:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Package
      run: |
        export THEOS=/opt/theos
        make package FINALPACKAGE=1
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-package
        path: packages/*.deb
